apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: saudenold
type: Opaque
stringData:
  API_KEY: ""  # Será gerado automaticamente ou definido manualmente
  DATABASE_PASSWORD: saudenold123  # Deve ser alterado em produção

