apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saudenold

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-ingress.yaml





